# Starter pipeline for building and packaging an ASP.NET project

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'
  imageName: 'webapplegacywin'
  baseImage: "mcr.microsoft.com/dotnet/framework/aspnet:4.8.1"
  kubernetesManifest: '$(Build.ArtifactStagingDirectory)/k8s/deployment.yaml'
  REPLICAS: 1
  IMAGE_TAG: $(Build.BuildId)
  DEPLOYMENT_NAME: 'webapplegacywin'

  
steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: FileTransform@2
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/'
    xmlTargetFiles: 'Web.config'
    
- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PublishUrl=$(Build.ArtifactStagingDirectory)/app.publish /p:Configuration=$(buildConfiguration)'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  

- task: RegExMatchReplace@2
  inputs:
    PathToFile: '$(Build.SourcesDirectory)/k8s/deployment.yaml'
    RegEx: ':latest'
    ValueToReplace: ':$(IMAGE_TAG)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/k8s/deployment.yaml'
    ArtifactName: 'manifests'
    publishLocation: 'Container'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/k8s'
    Contents: 'deployment.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/k8s'  

- task: Docker@2
  inputs:
    containerRegistry: 'acrRegistryConnection' 
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)    


- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'winPoolK8sConnection'
    namespace: 'apis'
    manifests: '$(kubernetesManifest)'
    

