# Starter pipeline for building and packaging an ASP.NET project

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'akhan2017/webapplegacywin'
  baseImage: "mcr.microsoft.com/dotnet/framework/aspnet:4.8.1"
  
steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:OutDir=$(Build.ArtifactStagingDirectory)/app.publish/'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'


- task: Docker@2
  inputs:
    containerRegistry: 'acrRegistryConnection' 
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'winPoolK8sConnection'
    namespace: 'apis'
    manifests: '$(Pipeline.Workspace)/k8s/deployment.yaml'