# Starter pipeline for building and packaging an ASP.NET project

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'
  imageName: 'webapplegacywin'
  baseImage: "mcr.microsoft.com/dotnet/framework/aspnet:4.8.1"
  kubernetesManifest: '$(Build.ArtifactStagingDirectory)/k8s/deployment.yaml'
  REPLICAS: 1
  IMAGE_TAG: $(Build.BuildId)
  DEPLOYMENT_NAME: 'webapplegacywin'

  
steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: FileTransform@2
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/'
    xmlTargetFiles: 'Web.config'
    
- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:OutDir=$(Build.ArtifactStagingDirectory)/app.publish/ /p:Configuration=$(buildConfiguration)'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/LogMonitor'  
    Contents: '**/*'                                     
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app.publish/LogMonitor' 

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/batch'  
    Contents: '**/*'                                    
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app.publish/batch'  


- task: RegExMatchReplace@2
  inputs:
    PathToFile: '$(Build.SourcesDirectory)/k8s/deployment.yaml'
    RegEx: ':latest'
    ValueToReplace: ':$(IMAGE_TAG)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/k8s/deployment.yaml'
    ArtifactName: 'manifests'
    publishLocation: 'Container'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/k8s'
    Contents: 'deployment.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/k8s'  
    
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'sc-keyvault'
    KeyVaultName: 'aksdevvault'
    SecretsFilter: '*'
    RunAsPreJob: true
    
- script: |
    echo $(DefaultConnection)
  displayName: 'Print connectionString'
  

- script: |
    secret=$(DefaultConnection)
    firstThreeChars=${secret:0:3}
    secretLength=${#secret}
    echo "First 3 characters of the secret: $firstThreeChars"
    echo "Total length of the secret: $secretLength"
  displayName: 'Print first 3 characters and length of connectionString'

- script: |
    keyv=${encryptionkey}
    firstThreeChars=${encryptionkey:0:3}
    echo "First 3 characters of the secret: $firstThreeChars"
  displayName: 'Print encryptionKey'
  
- task: Docker@2
  inputs:
    containerRegistry: 'akhanacrRegistryConnection' 
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.ArtifactStagingDirectory)/app.publish'
    tags: |
      $(Build.BuildId)    


- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'winPoolK8sConnection'
    namespace: 'apis'
    manifests: '$(kubernetesManifest)'
    

