apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplegacywin
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-legacy-win
  template:
    metadata:
      labels:
        app: webapp-legacy-win
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: webapplegacywin
        image: akhanacr.azurecr.io/webapplegacywin:latest
        ports:
        - containerPort: 80
