apiVersion: apps/v1
kind: Deployment
metadata:
  name: __DEPLOYMENT_NAME__
  namespace: apis
spec:
  replicas: __REPLICAS__
  selector:
    matchLabels:
      app: webapp-legacy-win
  template:
    metadata:
      labels:
        app: webapp-legacy-win
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: webapplegacywin
        image: akhanacr.azurecr.io/webapplegacywin:__IMAGE_TAG__
        ports:
        - containerPort: 80
